#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXTERNAL_DIR="${ROOT_DIR}/external"
ALATE_DIR="${EXTERNAL_DIR}/alate"
NEMALA_CORE_DIR="${EXTERNAL_DIR}/nemala_core"
WS_DIR="${ROOT_DIR}/ws"
WS_SRC_DIR="${WS_DIR}/src"
CONFIG_DIR="${ROOT_DIR}/config"
LOG_DIR="${ROOT_DIR}/logs"
PATCH_DIR="${ROOT_DIR}/patches"
DOCKER_DIR="${ROOT_DIR}/docker"
MANIFEST_FILE="${ROOT_DIR}/manifests/stack.repos"

STACK_NAME="${STACK_NAME:-mars-decision-stack}"
IMAGE="${IMAGE:-mars-decision-stack:local}"
NETWORK="${NETWORK:-${STACK_NAME}-net}"
VOLUME="${VOLUME:-${STACK_NAME}-ipc}"
ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-42}"
SITL_IMAGE="${SITL_IMAGE:-davidovrat/arducopter-sitl@sha256:acc41a3e9897ffae32c8d0f1c0787c5a10ca39119a5066651848771ed4fdef67}"
NEMALA_TOOLS_IMAGE="${NEMALA_TOOLS_IMAGE:-nemala/tools@sha256:471f1261c51932bec05a771d49545172b2b01e791de7425d1b4e10de06b9b8a3}"

export ROOT_DIR EXTERNAL_DIR ALATE_DIR NEMALA_CORE_DIR WS_DIR WS_SRC_DIR CONFIG_DIR LOG_DIR PATCH_DIR DOCKER_DIR MANIFEST_FILE
export STACK_NAME IMAGE NETWORK VOLUME ROS_DOMAIN_ID SITL_IMAGE NEMALA_TOOLS_IMAGE
